module.exports = {
  db: 'knex',
  conn: 'knex1',
  name: 'flights',
  create: true,
  update: true,
  delete: 0,
  import: true,
  export: true,
  multiSelect: false, // multiple selection
  cols: {
    flight_number: { // primary key column
      label: 'ID',
      // auto: 'pk',
      // hide: true,
      // add: 'readonly',
      // edit: 'readonly',
      multiKey: true,
    },
    status: {
      label: 'Status',
      type: 'string',
      filter: true,
      default: '',
      ui: {
        tag: 'input',
        // attrs: { type: 'file' }
      },
    },
    createdAt: {
      label: 'Created At',
      auto: 'ts', // autogenerated field... user = user id, ts = timestamp, pk = autogenerated primary key
      hide: true,
      add: 'hide',
      edit: 'readonly'
    },
    updatedAt: {
      label: 'Updated At',
      auto: 'ts',
      hide: true,
      add: 'hide',
      edit: 'readonly'
    }
  },

  // generated values
  pk: '',
  multiKey: [],
  required: [],
  auto: [],
  nonAuto: []
  // {id: 1, name: 'book1', categoryId: 1, rating: 5, yearPublished: '2004', created_at: mkDt() },
}
